// CRM サイドバー(リボン)の構成。スマート葬儀の実画面(トップ リボン展開状態)に準拠。
export interface NavNode { label: string; href?: string; children?: NavNode[]; icon?: string }

export const CRM_NAV: NavNode[] = [
  { label: "顧客管理", icon: "Users", children: [{ label: "顧客", href: "/kanri/customers" }] },
  { label: "請求管理", icon: "Receipt", children: [
    { label: "見積もり", href: "/kanri/estimates" },
    { label: "請求書", href: "/kanri/billing" },
    { label: "入金管理", href: "/kanri/deposits" },
    { label: "領収書", href: "/kanri/receipts" },
    { label: "売掛残高", href: "/kanri/receivables" },
  ] },
  { label: "発注管理", icon: "ShoppingCart", children: [
    { label: "発注", href: "/kanri/orders" },
    { label: "納品管理", href: "/kanri/deliveries" },
    { label: "買掛残高", href: "/kanri/payables" },
  ] },
  { label: "スケジュール管理", icon: "CalendarDays", children: [
    { label: "直近予定", href: "/kanri/schedule" },
    { label: "カレンダー", href: "/kanri/schedule/calendar" },
    { label: "イベント", href: "/kanri/schedule/events" },
    { label: "当番表", href: "/kanri/schedule/rota" },
  ] },
  { label: "AI遺影写真", icon: "ImageIcon", href: "/kanri/ai-portrait" },
  { label: "分析", icon: "LineChart", children: [
    { label: "売上実績", href: "/kanri/analytics" },
    { label: "売上分析", href: "/kanri/analytics/sales" },
    { label: "EC売上", href: "/kanri/analytics/ec" },
    { label: "発注分析", href: "/kanri/analytics/orders" },
  ] },
  { label: "SMS", icon: "Send", children: [{ label: "送信", href: "/kanri/sms" }] },
  // 設定メニュー: 実スマート葬儀のリボン(設定展開時)の項目・順序に準拠
  { label: "設定", icon: "Settings", children: [
    { label: "基本", children: [
      { label: "会社情報", href: "/kanri/settings/company" },
      { label: "組織管理", href: "/kanri/settings/organization" },
      { label: "計上組織マスター", href: "/kanri/settings/chartered_organization" },
      { label: "ユーザー管理", href: "/kanri/settings/users" },
      { label: "エリア", href: "/kanri/settings/area" },
      { label: "会場", href: "/kanri/settings/venue" },
      { label: "斎場/火葬場", href: "/kanri/settings/crematorium" },
      { label: "CRM入力必須項目設定", href: "/kanri/settings/required-fields" },
      { label: "葬儀の通知設定", href: "/kanri/settings/notice_setting_funeral" },
      { label: "発行会社", href: "/kanri/settings/org_company" },
      { label: "備考欄テンプレート", href: "/kanri/settings/note_master" },
      { label: "共有ファイル", href: "/kanri/settings/shared_file" },
      { label: "トークマニュアル", href: "/kanri/settings/talk_manual" },
    ] },
    { label: "顧客", children: [
      { label: "顧客種別", href: "/kanri/settings/customer_kind" },
      { label: "流入経路", href: "/kanri/settings/inflow" },
      { label: "顧客ステータス", href: "/kanri/settings/state" },
      { label: "顧客対応履歴テンプレート", href: "/kanri/settings/customer_comment_template" },
      { label: "対応履歴用タグ", href: "/kanri/settings/customer_comment_tag" },
      { label: "葬家タグ", href: "/kanri/settings/customer_funeral_target_tag" },
      { label: "葬家CSVダウンロード条件マスター", href: "/kanri/settings/customer_funeral_target_csv_condition" },
      { label: "会員種別", href: "/kanri/settings/membership" },
      { label: "会員特典", href: "/kanri/settings/member_benefit" },
      { label: "会員ステータス", href: "/kanri/settings/member_status" },
      { label: "会員分類", href: "/kanri/settings/member_plan" },
    ] },
    { label: "葬儀", children: [
      { label: "葬儀種別", href: "/kanri/settings/funeral_kind" },
      { label: "葬家ステータス", href: "/kanri/settings/phase" },
      { label: "宗教者", href: "/kanri/settings/my_temple" },
      { label: "宗教者用エリア", href: "/kanri/settings/area_for_my_temple" },
      { label: "お迎え先", href: "/kanri/settings/pick_up_location" },
      { label: "安置希望場所", href: "/kanri/settings/target_desired_place" },
      { label: "対象者の担当者マスタ", href: "/kanri/settings/funeral_target_manager" },
      { label: "備考定型文", href: "/kanri/settings/remark" },
      { label: "搬送先", href: "/kanri/settings/transport_destination" },
      { label: "待合室", href: "/kanri/settings/lounge" },
      { label: "お清め方法", href: "/kanri/settings/purify_manner" },
      { label: "お清め場所", href: "/kanri/settings/purify_place" },
      { label: "乗車場所", href: "/kanri/settings/boarding_place" },
      { label: "車種", href: "/kanri/settings/car_model" },
      { label: "法要設定", href: "/kanri/settings/memorial_service" },
    ] },
    { label: "商品", children: [
      { label: "発注先", href: "/kanri/settings/supplier" },
      { label: "仕入区分", href: "/kanri/settings/purchase_category" },
      { label: "商品種別", href: "/kanri/settings/product_kind" },
      { label: "商品", href: "/kanri/products" },
      { label: "値引商品", href: "/kanri/settings/discounted_product" },
      { label: "セット商品", href: "/kanri/product-sets" },
      { label: "まとめ商品", href: "/kanri/settings/rough_product" },
      { label: "その他オプション、お供えにかかる費用", href: "/kanri/settings/rough_product_osonae" },
      { label: "発注指示テンプレート", href: "/kanri/settings/order_instruction_template" },
      { label: "売上区分", href: "/kanri/settings/sale_category" },
      { label: "サービス利用料", href: "/kanri/settings/service-fee" },
    ] },
    { label: "請求", children: [
      { label: "件名マスター", href: "/kanri/settings/estimate_title" },
      { label: "摘要設定", href: "/kanri/settings/purpose" },
      { label: "見積書テンプレート", href: "/kanri/settings/estimate_template" },
      { label: "請求書テンプレート", href: "/kanri/settings/invoice_template" },
      { label: "伝票（入金先）", href: "/kanri/settings/deposit_place" },
      { label: "伝票（入金区分）", href: "/kanri/settings/deposit_category" },
      { label: "入金方法", href: "/kanri/settings/payment_method" },
      { label: "入金種別", href: "/kanri/settings/payment_category" },
      { label: "請求書の補足情報", href: "/kanri/settings/invoice_additional_content" },
      { label: "但し書マスター", href: "/kanri/settings/proviso" },
    ] },
    { label: "スケジュール", children: [
      { label: "タイムスケジュール設定", href: "/kanri/settings/time_schedule_master" },
      { label: "イベント行動", href: "/kanri/settings/meeting_behavior" },
      { label: "イベント分類", href: "/kanri/settings/meeting_kind" },
      { label: "緊急連絡先", href: "/kanri/settings/emergency_contact" },
    ] },
    { label: "SMS", children: [
      { label: "SMS配信テンプレート", href: "/kanri/settings/sms_template" },
      { label: "SMS自動配信設定", href: "/kanri/settings/sms_auto_sent" },
    ] },
    { label: "アフターセールス", children: [
      { label: "ｱﾌﾀｰｾｰﾙｽ項目", href: "/kanri/settings/after_sale_item" },
      { label: "ｱﾌﾀｰｾｰﾙｽ用ステータス", href: "/kanri/settings/after_sale_action" },
      { label: "ｱﾌﾀｰｾｰﾙｽ用ステータス設定", href: "/kanri/settings/after_sale_item_action" },
    ] },
    { label: "その他", children: [
      { label: "提携先", href: "/kanri/settings/partner" },
      { label: "ブランド", href: "/kanri/settings/bland" },
    ] },
  ] },
];
